db.Part_B.insertOne({
  make: "Toyota",
  model: "Landcruiser",
  year: 2019,
  odometer: 44296,
  dealershipInformation: {
    condition: "Excellent",
    arrivalDate: "10-03-2021",
    location: "QLD",
    status: "on sale",
    pricePaid: 68000,
    transmission: "mannual",
  },
  features: [
    "Aux Input Socket",
    "Aux Input USB Socket",
    "Input for IPod",
    "MP3 Decoder",
    "CD Player",
    "2 Speaker Stereo",
    "Power Antenna",
  ],
  listPrice: 76880,
});

db.Part_B.insertOne({
  make: "Hyundai",
  model: "i30",
  year: 2020,
  odometer: 22328,
  dealershipInformation: {
    condition: "Excellent",
    arrivalDate: "21-05-2021",
    location: "QLD",
    status: "on sale",
    pricePaid: 26000,
    transmission: "automatic",
  },
  features: [
    "Aux Input Socket",
    "Aux Input USB Socket",
    "Input for IPod",
    "Muti-function Control Screen - Colour",
    "Smart Device Integration - Android Auto/Apple CarPlay",
    "Wireless Charging - Compatible Devices",
    "7 Speaker Stereo",
    "Digital Radio Receiver (DAB+)",
  ],
  listPrice: 34990,
});

db.Part_B.insertOne({
  make: "Ford",
  model: "Ranger Raptor PX MKIII",
  year: 2019,
  odometer: 37654,
  dealershipInformation: {
    condition: "Good",
    arrivalDate: "26-11-2020",
    location: "NSW",
    status: "on sale",
    pricePaid: 69000,
    transmission: "automatic",
  },
  features: [
    "Bluetooth",
    "Aux Input USB Socket",
    "Muti-function Control Screen - Colour",
    "Smart Device Integration - Android Auto/Apple CarPlay",
    "CD Player",
    "Wireless Charging - Compatible Devices",
    "6 Speaker Stereo",
    "Digital Radio Receiver (DAB+)",
  ],
  listPrice: 77990,
});

db.Part_B.insertOne({
  make: "Toyota",
  model: "Corolla SX Hybrid",
  year: 2020,
  odometer: 13733,
  dealershipInformation: {
    condition: "Excellent",
    arrivalDate: "12-07-2021",
    location: "VIC",
    status: "on sale",
    pricePaid: 28000,
    transmission: "automatic",
  },
  features: [
    "Smart key",
    "Bluetooth",
    "Aux Input USB Socket",
    "Muti-function Control Screen - Colour",
    "Smart Device Integration - Android Auto/Apple CarPlay",
    "Smart Device App Display/Control",
    "Wireless Charging - Compatible Devices",
    "6 Speaker Stereo",
    "Digital Radio Receiver (DAB+)",
  ],
  listPrice: 33799,
});
